build-buster:
  image: jegopozo/linux-build:debian-buster
  stage: build
  variables:
    cc: "gcc -g -std=gnu99 -wall -werror -wextra -wshadow -pedantic -winit-self -wswitch-default -wswitch-enum"
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make check

build-bullseye:
  image: jegopozo/linux-build:debian-bullseye
  stage: build
  variables:
    cc: "gcc -g -std=gnu99 -wall -werror -wextra -wshadow -pedantic -winit-self -wswitch-default -wswitch-enum"
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
