stages:
  - build
  - test


.strech_image: &stretch
  image: registry.gitlab.com/schabe/synodl:debian-stretch

.buster_image: &buster
  image: registry.gitlab.com/schabe/synodl:debian-buster

.bullseye_image: &bullseye
  image: registry.gitlab.com/schabe/synodl:debian-bullseye


.build: &build
  stage: build
  variables:
    CFLAGS: "-std=gnu99 -Wall -Werror -Wextra -Wshadow -pedantic -Winit-self -Wswitch-default -Wswitch-enum"
  script:
    - ./autogen.sh
    - ./configure
    - make

.test: &test
  stage: test
  variables:
    CFLAGS: "-g -std=gnu99 -Wall -Werror -Wextra -Wshadow -pedantic -Winit-self -Wswitch-default -Wswitch-enum -O0"
  script:
    - ./autogen.sh
    - ./configure
    - scan-build --status-bugs make
    - make check
    - valgrind --leak-check=full --error-exitcode=1 ./src/test_ui_util

.coverage: &coverage
  stage: test
  variables:
    CFLAGS: "-fprofile-arcs -ftest-coverage -fPIC -O0"
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - gcovr -r src/


stretch:build:
  <<: *stretch
  <<: *build

stretch:test:
  <<: *stretch
  <<: *test

buster:build:
  <<: *buster
  <<: *build

buster:test:
  <<: *buster
  <<: *test

bullseye:build:
  <<: *bullseye
  <<: *build

bullseye:test:
  <<: *bullseye
  <<: *test

coverage:
  <<: *bullseye
  <<: *coverage
