stages:
  - build
  - test

.build: &build
  stage: build
  variables:
    CFLAGS: "-std=gnu99 -Wall -Werror -Wextra -Wshadow -pedantic -Winit-self -Wswitch-default -Wswitch-enum"
  script:
    - ./autogen.sh
    - ./configure
    - make

.test: &test
  stage: test
  variables:
    CFLAGS: "-g -std=gnu99 -Wall -Werror -Wextra -Wshadow -pedantic -Winit-self -Wswitch-default -Wswitch-enum -O0"
  script:
    - ./autogen.sh
    - ./configure
    - scan-build --status-bugs make
    - make check
    - valgrind --leak-check=full --error-exitcode=1 ./src/test_ui_util

.strech_image: &stretch
  image: jegopozo/linux-build:debian-stretch

.buster_image: &buster
  image: jegopozo/linux-build:debian-buster

.bullseye_image: &bullseye
  image: jegopozo/linux-build:debian-bullseye

stretch:build:
  <<: *stretch
  <<: *build

stretch:test:
  <<: *stretch
  <<: *test

buster:build:
  <<: *buster
  <<: *build

buster:test:
  <<: *buster
  <<: *test

bullseye:build:
  <<: *bullseye
  <<: *build

bullseye:test:
  <<: *bullseye
  <<: *test
